### PR TITLE
Fix: Merged the rubocop matrics duplication in config

### PR DESCRIPTION
**Pull request by akhilgkrishnan**
This PR removes the duplicated the rubocop matric from `rubocop.yml`.

### CODE REVIEW

**Comment by subintp** [comment]
@akhilgkrishnan  Thanks for the PR. Can you raise this PR to `multiwoven-server` ?

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan Thanks for the PR. Can you raise this PR to `multiwoven-server` ?

Sure, I can do that. Also any reason for keeping code in two places?

**Comment by akhilgkrishnan** [comment]
@subintp Raised a PR https://github.com/Multiwoven/multiwoven-server/pull/78

**Comment by akhilgkrishnan** [comment]
@subintp Raised a new PR https://github.com/Multiwoven/multiwoven-server/pull/78

**Pull request closed without merging**
